In [190]:
# Importing essential libraries
import pandas as pd
import numpy as np

# Loading the datasets
df = pd.read_csv('dataset/ipl.csv')

In [191]:
df.head()

mid        date                  venue               bat_team  \
0    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
1    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
2    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
3    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   
4    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders   

                     bowl_team      batsman   bowler  runs  wickets  overs  \
0  Royal Challengers Bangalore   SC Ganguly  P Kumar     1        0    0.1   
1  Royal Challengers Bangalore  BB McCullum  P Kumar     1        0    0.2   
2  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.2   
3  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.3   
4  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.4   

   runs_last_5  wickets_last_5  striker  non-striker  total  
0            1               0        0            0    222  
1            1               0        0            0    222  
2            2               0        0            0    222  
3            2               0        0            0    222  
4            2               0        0            0    222

In [192]:
# Data Cleaning
# Removing Unwanted columns
columns_to_remove = ['mid','batsman','bowler','striker','non-striker','venue']
df.drop(labels = columns_to_remove, axis=1, inplace=True)

In [193]:
df.head()

date               bat_team                    bowl_team  runs  \
0  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     1   
1  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     1   
2  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     2   
3  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     2   
4  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore     2   

   wickets  overs  runs_last_5  wickets_last_5  total  
0        0    0.1            1               0    222  
1        0    0.2            1               0    222  
2        0    0.2            2               0    222  
3        0    0.3            2               0    222  
4        0    0.4            2               0    222

In [194]:
df['bat_team'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians', 'Deccan Chargers', 'Kings XI Punjab',
       'Royal Challengers Bangalore', 'Delhi Daredevils',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant'], dtype=object)

In [195]:
# Keeping only consistent teams
consistent_teams = ['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians','Kings XI Punjab','Royal Challengers Bangalore', 'Delhi Daredevils',
       'Sunrisers Hyderabad',
       ]

In [196]:
df = df[(df['bat_team'].isin(consistent_teams)) & (df['bowl_team'].isin(consistent_teams)) ]

In [197]:
# Removing the first 5 overs data in every match
df= df[df['overs']>=5.0]

In [198]:
df.head()

date               bat_team                    bowl_team  runs  \
32  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
33  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
34  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
35  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   
36  2008-04-18  Kolkata Knight Riders  Royal Challengers Bangalore    61   

    wickets  overs  runs_last_5  wickets_last_5  total  
32        0    5.1           59               0    222  
33        1    5.2           59               1    222  
34        1    5.3           59               1    222  
35        1    5.4           59               1    222  
36        1    5.5           58               1    222

In [199]:
print(df['bat_team'].unique())
print(df['bowl_team'].unique())

['Kolkata Knight Riders' 'Chennai Super Kings' 'Rajasthan Royals'
 'Mumbai Indians' 'Kings XI Punjab' 'Royal Challengers Bangalore'
 'Delhi Daredevils' 'Sunrisers Hyderabad']
['Royal Challengers Bangalore' 'Kings XI Punjab' 'Delhi Daredevils'
 'Rajasthan Royals' 'Mumbai Indians' 'Chennai Super Kings'
 'Kolkata Knight Riders' 'Sunrisers Hyderabad']


In [200]:
# Converting the column 'date' from string into datetime object
from datetime import datetime
df['date'] = df['date'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d'))

In [201]:
# Data Processing
# Converting Categorical Features using OneHotEnconding method
encoded_df = pd.get_dummies(data=df, columns=['bat_team','bowl_team'])

In [202]:
encoded_df.head()

date  runs  wickets  overs  runs_last_5  wickets_last_5  total  \
32 2008-04-18    61        0    5.1           59               0    222   
33 2008-04-18    61        1    5.2           59               1    222   
34 2008-04-18    61        1    5.3           59               1    222   
35 2008-04-18    61        1    5.4           59               1    222   
36 2008-04-18    61        1    5.5           58               1    222   

    bat_team_Chennai Super Kings  bat_team_Delhi Daredevils  \
32                             0                          0   
33                             0                          0   
34                             0                          0   
35                             0                          0   
36                             0                          0   

    bat_team_Kings XI Punjab  ...  bat_team_Royal Challengers Bangalore  \
32                         0  ...                                     0   
33                         0  ...                                     0   
34                         0  ...                                     0   
35                         0  ...                                     0   
36                         0  ...                                     0   

    bat_team_Sunrisers Hyderabad  bowl_team_Chennai Super Kings  \
32                             0                              0   
33                             0                              0   
34                             0                              0   
35                             0                              0   
36                             0                              0   

    bowl_team_Delhi Daredevils  bowl_team_Kings XI Punjab  \
32                           0                          0   
33                           0                          0   
34                           0                          0   
35                           0                          0   
36                           0                          0   

    bowl_team_Kolkata Knight Riders  bowl_team_Mumbai Indians  \
32                                0                         0   
33                                0                         0   
34                                0                         0   
35                                0                         0   
36                                0                         0   

    bowl_team_Rajasthan Royals  bowl_team_Royal Challengers Bangalore  \
32                           0                                      1   
33                           0                                      1   
34                           0                                      1   
35                           0                                      1   
36                           0                                      1   

    bowl_team_Sunrisers Hyderabad  
32                              0  
33                              0  
34                              0  
35                              0  
36                              0  

[5 rows x 23 columns]

In [203]:
# Splitting data into train and test set
x_train = encoded_df.drop(labels='total', axis=1)[encoded_df['date'].dt.year <=2016]
x_test = encoded_df.drop(labels='total', axis=1)[encoded_df['date'].dt.year >=2017]

In [204]:
y_train = encoded_df[encoded_df['date'].dt.year <=2016]['total'].values
y_test = encoded_df[encoded_df['date'].dt.year >=2017]['total'].values

In [205]:
# Removing the 'date' column
x_train.drop(labels='date', axis=True, inplace=True)
x_test.drop(labels='date', axis=True, inplace=True)

In [206]:
# Model Building
# Linear Regression Model
import sklearn
from sklearn.linear_model import LinearRegression

In [207]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [208]:
y_pred = lr.predict(x_test)

In [209]:
y_test[0:5], y_pred[0:5]

(array([207, 207, 207, 207, 207], dtype=int64),
 array([172.07093429, 175.2197967 , 174.61607874, 177.76494115,
        180.93050818]))

In [210]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

251.0079231041729

In [ ]:
# Ridge regression Model

In [211]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [212]:
ridge = Ridge()

In [213]:
ridge.fit(x_train,y_train)

Ridge()

In [214]:
y_pred = ridge.predict(x_test)

In [215]:
y_test[0:5], y_pred[0:5]

(array([207, 207, 207, 207, 207], dtype=int64),
 array([172.07039802, 175.21930041, 174.61555435, 177.76445674,
        180.93004647]))

In [216]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

251.00850756690326

In [217]:
encoded_df.columns

Index(['date', 'runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5',
       'total', 'bat_team_Chennai Super Kings', 'bat_team_Delhi Daredevils',
       'bat_team_Kings XI Punjab', 'bat_team_Kolkata Knight Riders',
       'bat_team_Mumbai Indians', 'bat_team_Rajasthan Royals',
       'bat_team_Royal Challengers Bangalore', 'bat_team_Sunrisers Hyderabad',
       'bowl_team_Chennai Super Kings', 'bowl_team_Delhi Daredevils',
       'bowl_team_Kings XI Punjab', 'bowl_team_Kolkata Knight Riders',
       'bowl_team_Mumbai Indians', 'bowl_team_Rajasthan Royals',
       'bowl_team_Royal Challengers Bangalore',
       'bowl_team_Sunrisers Hyderabad'],
      dtype='object')

In [218]:
#from sklearn.model_selection import train_test_split
#x = encoded_df.drop('total', axis=1)
#y = encoded_df['total']